### ISSUE TITLE
Remove ambiguous characters

### ISSUE THREAD

**Issue by JeroenSormani** [JeroenSormani/woocommerce-coupon-generator#14]
1, i, l, o, 0

**Comment by JeroenSormani** [comment]
So far not heard of any(one?) running into issues about this. Guessing coupons are most likely copied anyways. Closing till I head sounds this needs improving.

**Comment by loafcoop** [comment]
This has been bugging me for a few years as our customers often receive a printout of the PDF and have to type it in, and they ALWAYS mess up 1, i, l, o, 0. It would be fantastic if they weren't included.  (Speaking as someone who uses Woocommerce daily, not as a developer).

(A side-fix would be to never display codes in capitals.)
