### ISSUE TITLE
Some options are not put into generated coupons

### ISSUE THREAD

**Issue by n9yty** [JeroenSormani/woocommerce-coupon-generator#20]
There are other plugins, like Subscriptions, that are generating other fields that are visible during the coupon generation process but the values are not saved in the generated coupons.

**Comment by n9yty** [comment]
Realizing that there are too many third-party plugins to probably support directly, I put in pull request #23 as a possibly better approach to #22 as it would allow each site to extend the supported fields. They would still have to determine what the form fields were and how to capture the data, but it would then make it user/site extensible rather than trying to accommodate every variation in the core plugin.

**Comment by JeroenSormani** [comment]
Hey, sorry for not responding earlier!

Can you tell me how your #23 filter is different from the existing filter? I don't believe there's any difference and it has been possible to add additional meta data from the start. 

(closing for now)

**Comment by n9yty** [comment]
I don't recall being able to make what we needed work with existing filters, but it is possible I missed it. Your reply would have been more helpful had you pointed out the use case and implementation.  In my pull request I had given an example of how I was intending to use it, so if that can be duplicated with existing filters it would have been great to see it.

**Comment by n9yty** [comment]
Looking at the pull request (it was a long time ago) it seems I may have moved your filter down below because I had also added another one? But that is the problem with so much time having passed between when I was working on this and knew why it seemed necessary and now. :)

**Comment by n9yty** [comment]
Ok, I think I see the difference. Your filter was not passing $args in which I needed to be available to do whatever it was that we were doing. Again, I'm fuzzy at this point. Strangely enough this has just come back up here and I need to generate some sets of codes. But that is what I see in the code as far as differences between the original filter and what I put in, the $args array, and what that opened up in terms of making changes.

**Comment by n9yty** [comment]
It also have may be that I broke it out into two filters at the bottom so that anyone who had set up the existing filter wouldn't experience code breakage by changing it underneath them. This way they would get the data with any extra fields but wouldn't have to worry about the extra $args being sent.
