### ISSUE TITLE
How do I use a filter to customise the coupon format?

### ISSUE THREAD

**Issue by mcometa** [JeroenSormani/woocommerce-coupon-generator#28]
How do I use a filter to customise the coupon format?

**Comment by JeroenSormani** [comment]
The filter here can be used to change the generated code; https://github.com/JeroenSormani/woocommerce-coupon-generator/blob/32af4fb7a39a2128b3857a1de6e0db72124b3db7/includes/admin/wccg-core-functions.php#L144

**Comment by mcometa** [comment]
Thank you very much. I have already implemented this.
