### ISSUE TITLE
I was able to create duplicates

### ISSUE THREAD

**Issue by inovek** [JeroenSormani/woocommerce-coupon-generator#6]
Hello,

I played a little bit with the **wccg_get_random_coupon()**-function around (just for another format and prefix) and realized that coupons don't get checked before the creation.  I was able to create duplicates.

It isn't a real problem for me, but a user wouldn't recognize this.

**Comment by JeroenSormani** [comment]
Hey @inovek,

Correct, it is possible duplicate coupons are generated. The changes to that are quite small though as there are 62<sup>12</sup> (thats, like, a million-gazillion-empirerillion) possibilities, so I don't tend worry too much about those odds ;-)

Adding a check for existing coupons would give a huge slow down on the generation of the coupons (I've done a sh*t ton of testing and optimization on the generation process, including a check for existing coupon codes :-)

**Comment by inovek** [comment]
But I think it would be a good idea to add this option. Especially when you allow in the future to change the length of the coupon-code and add prefixes, then such an toggleable option would be nice.

Just because you say there are so much possibilities, that it wouldn't happen. (it still remains possible)

**Comment by JeroenSormani** [comment]
I'll take it in consideration as a option, but can't guarantee it.
So far I've not been very convinced of the amount of added value of it (I'm very careful with adding options to keep my plugins clean & lean). 

Even when it happens that a duplicate coupon code is generated, the impact of that is almost irrelevant I believe.. (correct me if I'm wrong)
